local lt = require 'test.ltest'

---@return Moe.Player
local function newPlayer()
    local system = moe.attribute.create()
    return moe.player.create { attributes = system:createInstance() }
end

lt.test('桌子：座位号决定行动顺序', function ()
    local desk = moe.desk.create(3)
    local a    = newPlayer()
    local b    = newPlayer()
    local c    = newPlayer()
    desk:sit(1, a)
    desk:sit(2, b)
    desk:sit(3, c)

    lt.assertEquals('1 号位的下一个是 2 号位', b, desk:getNext(a))
    lt.assertEquals('再下一个是 3 号位', c, desk:getNext(b))
    lt.assertEquals('3 号位之后回到 1 号位', a, desk:getNext(c))
    lt.assertEquals('座位列表按座位号升序', 3, #desk:getPlayers())
    lt.assertEquals('第一个是 1 号位', a, desk:getPlayers()[1])
    lt.assertEquals('1 号位上的玩家查得到', a, desk:getPlayer(1))
    lt.assertEquals('玩家能查出自己的座位号', 2, desk:getIndex(b))
end)

lt.test('桌子：跳过不参与行动的玩家', function ()
    local desk = moe.desk.create(3)
    local a    = newPlayer()
    local b    = newPlayer()
    local c    = newPlayer()
    desk:sit(1, a)
    desk:sit(2, b)
    desk:sit(3, c)

    b:setActing(false)
    lt.assertEquals('跳过被标记的玩家', c, desk:getNext(a))

    b:setActing(true)
    lt.assertEquals('重新参与后又排进来', b, desk:getNext(a))
end)

lt.test('桌子：跳过空座位', function ()
    local desk = moe.desk.create(5)
    local a    = newPlayer()
    local b    = newPlayer()
    desk:sit(1, a)
    desk:sit(4, b)

    lt.assertEquals('从 1 号位直接跳到 4 号位', b, desk:getNext(a))
    lt.assertEquals('从 4 号位绕回 1 号位', a, desk:getNext(b))
    lt.assertEquals('座位列表只有两个玩家', 2, #desk:getPlayers())
end)

lt.test('桌子：同一座位与相邻座位距离都是 1', function ()
    local desk = moe.desk.create(8)
    local a    = newPlayer()
    local b    = newPlayer()
    desk:sit(1, a)
    desk:sit(2, b)

    lt.assertEquals('相邻座位是 1', 1, desk:getDistance(a, b))
    lt.assertEquals('自己到自己也是 1', 1, desk:getDistance(a, a))
end)

lt.test('桌子：沿较短方向计算距离', function ()
    local desk = moe.desk.create(8)
    local a    = newPlayer()
    local b    = newPlayer()
    local c    = newPlayer()
    desk:sit(1, a)
    desk:sit(5, b)
    desk:sit(8, c)

    lt.assertEquals('8 座桌上 1 号到 5 号是 4', 4, desk:getDistance(a, b))
    lt.assertEquals('8 座桌上 1 号到 8 号是 1（另一个方向）', 1, desk:getDistance(a, c))
    lt.assertEquals('距离与方向对称', 4, desk:getDistance(b, a))
end)

lt.test('桌子：距离按座位总数求值', function ()
    local wide   = moe.desk.create(8)
    local narrow = moe.desk.create(5)
    local a      = newPlayer()
    local b      = newPlayer()
    wide:sit(1, a)
    wide:sit(5, b)
    narrow:sit(1, a)
    narrow:sit(5, b)

    lt.assertEquals('8 座桌上是 4', 4, wide:getDistance(a, b))
    lt.assertEquals('5 座桌上是 1', 1, narrow:getDistance(a, b))
end)

lt.test('桌子：非法入座报错', function ()
    local desk = moe.desk.create(3)
    local a    = newPlayer()
    local b    = newPlayer()
    desk:sit(1, a)

    lt.assertError('同一个座位不能坐两个人', function ()
        desk:sit(1, b)
    end)
    lt.assertError('座位号越界报错', function ()
        desk:sit(4, b)
    end)
    lt.assertError('座位号不是整数报错', function ()
        desk:sit(1.5, b)
    end)
end)

lt.test('桌子：不在桌上的玩家不能参与求值', function ()
    local desk = moe.desk.create(3)
    local a    = newPlayer()
    local b    = newPlayer()
    desk:sit(1, a)

    lt.assertError('没入座的玩家没有下一个行动者', function ()
        desk:getNext(b)
    end)
    lt.assertError('没入座的玩家不参与距离求值', function ()
        desk:getDistance(a, b)
    end)
end)
