test.require 'test.core.random'
test.require 'test.core.card'
test.require 'test.core.zone'
test.require 'test.core.move'
test.require 'test.core.attribute'
test.require 'test.core.scenario'
test.require 'test.core.reload'
