---@meta

--- 装备子区名单挂在装载器给的共享袋上（内容侧跨包共享；装载器每轮新建一张）
---@class Loader.Rule
---@field equipZones? string[]
---@field ownZones? string[]
---@field defaultHp? integer
---@field lordHpBonus? integer
---@field defaultDrawCount? integer
---@field phases? string[]

--- 性别（由武将写入；没有武将时常常没有 —— 官方：没有性别的角色不能判断别人与其性别是否相同）
---@alias 基础.性别 '男'|'女'

--- 势力（由武将写入；官方：魏 / 蜀 / 吴 / 群 / 西 / 神，标准包只用前四个）
---@alias 基础.势力 '魏'|'蜀'|'吴'|'群'

---@class Player: Class.Base
---@field sex? 基础.性别
---@field hero? HeroDef # 这名角色用的是哪张武将（由 @基础/武将.lua 的 setHero 写入）
---@field kingdom? 基础.势力 # 势力（同上）
---@field getAttr fun(self: Player, name: '体力'|'体力上限'|'攻击范围'|'进攻修正'|'防御修正'): number
---@field getAttr fun(self: Player, name: string): any
---@field setAttr fun(self: Player, name: '体力'|'体力上限'|'攻击范围'|'进攻修正'|'防御修正', value: number)
---@field setAttr fun(self: Player, name: string, value: any)
---@field addAttr fun(self: Player, name: '体力'|'体力上限'|'攻击范围'|'进攻修正'|'防御修正', delta: number): fun()
---@field addAttr fun(self: Player, name: string, delta: any): fun()

--- 判定是本包提供的时机（内核不再认识它们）：按名收窄 `on` / `fire` 的载荷
---@class Game
---@field on fun(self: Game, name: '判定-前', callback: fun(judge: Judge): any): function
---@field fire fun(self: Game, name: '判定-前', judge: Judge): any # 改判窗口：只能在这里面换牌
---@field on fun(self: Game, name: '判定-后', callback: fun(judge: Judge): any): function
---@field fire fun(self: Game, name: '判定-后', judge: Judge): any

--- 判定的两条**对判定者再发一份**（全局先、当事人后；同名 —— 判定没有「来源 / 目标」之分）
---@class Player
---@field on fun(self: Player, name: '判定-前', callback: fun(judge: Judge): any): function
---@field fire fun(self: Player, name: '判定-前', judge: Judge): any
---@field on fun(self: Player, name: '判定-后', callback: fun(judge: Judge): any): function
---@field fire fun(self: Player, name: '判定-后', judge: Judge): any

--- 伤害与治疗的时机也由本包提供：按名收窄 `on` / `fire` 的载荷
--- 四个阶段各发三份（全局 / 来源 / 目标）：开始（仅通知，别改值）→ 生效前（改值的口子）→ 生效后（「受到伤害后」这类常用时机）→ 结束（全部结算完）
---@class Game
---@field on fun(self: Game, name: '伤害-开始', callback: fun(damage: Damage): any): function
---@field fire fun(self: Game, name: '伤害-开始', damage: Damage): any
---@field on fun(self: Game, name: '伤害-生效前', callback: fun(damage: Damage): any): function
---@field fire fun(self: Game, name: '伤害-生效前', damage: Damage): any
---@field on fun(self: Game, name: '伤害-生效后', callback: fun(damage: Damage): any): function
---@field fire fun(self: Game, name: '伤害-生效后', damage: Damage): any
---@field on fun(self: Game, name: '伤害-结束', callback: fun(damage: Damage): any): function
---@field fire fun(self: Game, name: '伤害-结束', damage: Damage): any
---@field on fun(self: Game, name: '治疗-开始', callback: fun(heal: Heal): any): function
---@field fire fun(self: Game, name: '治疗-开始', heal: Heal): any
---@field on fun(self: Game, name: '治疗-生效前', callback: fun(heal: Heal): any): function
---@field fire fun(self: Game, name: '治疗-生效前', heal: Heal): any
---@field on fun(self: Game, name: '治疗-生效后', callback: fun(heal: Heal): any): function
---@field fire fun(self: Game, name: '治疗-生效后', heal: Heal): any
---@field on fun(self: Game, name: '治疗-结束', callback: fun(heal: Heal): any): function
---@field fire fun(self: Game, name: '治疗-结束', heal: Heal): any

---@class Player: Class.Base
--- 伤害 / 治疗（本包提供）：来源侧与承受侧各再发一份
---@field on fun(self: Player, name: '伤害-来源-开始', callback: fun(damage: Damage): any): function
---@field fire fun(self: Player, name: '伤害-来源-开始', damage: Damage): any
---@field on fun(self: Player, name: '伤害-来源-生效前', callback: fun(damage: Damage): any): function
---@field fire fun(self: Player, name: '伤害-来源-生效前', damage: Damage): any
---@field on fun(self: Player, name: '伤害-来源-生效后', callback: fun(damage: Damage): any): function
---@field fire fun(self: Player, name: '伤害-来源-生效后', damage: Damage): any
---@field on fun(self: Player, name: '伤害-来源-结束', callback: fun(damage: Damage): any): function
---@field fire fun(self: Player, name: '伤害-来源-结束', damage: Damage): any
---@field on fun(self: Player, name: '伤害-目标-开始', callback: fun(damage: Damage): any): function
---@field fire fun(self: Player, name: '伤害-目标-开始', damage: Damage): any
---@field on fun(self: Player, name: '伤害-目标-生效前', callback: fun(damage: Damage): any): function
---@field fire fun(self: Player, name: '伤害-目标-生效前', damage: Damage): any
---@field on fun(self: Player, name: '伤害-目标-生效后', callback: fun(damage: Damage): any): function
---@field fire fun(self: Player, name: '伤害-目标-生效后', damage: Damage): any
---@field on fun(self: Player, name: '伤害-目标-结束', callback: fun(damage: Damage): any): function
---@field fire fun(self: Player, name: '伤害-目标-结束', damage: Damage): any
---@field on fun(self: Player, name: '治疗-来源-开始', callback: fun(heal: Heal): any): function
---@field fire fun(self: Player, name: '治疗-来源-开始', heal: Heal): any
---@field on fun(self: Player, name: '治疗-来源-生效前', callback: fun(heal: Heal): any): function
---@field fire fun(self: Player, name: '治疗-来源-生效前', heal: Heal): any
---@field on fun(self: Player, name: '治疗-来源-生效后', callback: fun(heal: Heal): any): function
---@field fire fun(self: Player, name: '治疗-来源-生效后', heal: Heal): any
---@field on fun(self: Player, name: '治疗-来源-结束', callback: fun(heal: Heal): any): function
---@field fire fun(self: Player, name: '治疗-来源-结束', heal: Heal): any
---@field on fun(self: Player, name: '治疗-目标-开始', callback: fun(heal: Heal): any): function
---@field fire fun(self: Player, name: '治疗-目标-开始', heal: Heal): any
---@field on fun(self: Player, name: '治疗-目标-生效前', callback: fun(heal: Heal): any): function
---@field fire fun(self: Player, name: '治疗-目标-生效前', heal: Heal): any
---@field on fun(self: Player, name: '治疗-目标-生效后', callback: fun(heal: Heal): any): function
---@field fire fun(self: Player, name: '治疗-目标-生效后', heal: Heal): any
---@field on fun(self: Player, name: '治疗-目标-结束', callback: fun(heal: Heal): any): function
---@field fire fun(self: Player, name: '治疗-目标-结束', heal: Heal): any
--- 兜底：跨文件加候选时必须自带（不带的话同名的整张候选表都不解析，见 architecture §9.6 配方）
---@field on fun(self: Player, name: string, callback: fun(payload: any): any): function
---@field fire fun(self: Player, name: string, ...: any): any

--- 技能定义上的钩子：`'被动'` 在**每次启用**时跑一次（如技能被克制 / 封印后恢复），要挂什么就 `host:bindGC(…)`
---@class SkillDef
---@field on fun(self: SkillDef, event: '被动', handler: fun(skill: Skill, host: GCHost)): SkillDef
---@field on fun(self: SkillDef, event: string, handler: function): SkillDef

--- 技能订阅时机的声明：`event` 订自己那份（`owner:on`）、`globalEvent` 订局那份（`game:on`）—— **只做订阅**，要不要发动由回调自己写（`skill:tryCast(…)`）
--- 本包提供的时机在这里按名收窄载荷（内核时机的候选在内核的 `env-meta.lua` 里）；伤害 / 治疗各四个阶段、来源侧与承受侧各一份
---@class SkillDef
---@field event fun(self: SkillDef, name: '伤害-目标-开始', handler: fun(skill: Skill, damage: Damage): any): SkillDef
---@field event fun(self: SkillDef, name: '伤害-目标-生效前', handler: fun(skill: Skill, damage: Damage): any): SkillDef
---@field event fun(self: SkillDef, name: '伤害-目标-生效后', handler: fun(skill: Skill, damage: Damage): any): SkillDef
---@field event fun(self: SkillDef, name: '伤害-目标-结束', handler: fun(skill: Skill, damage: Damage): any): SkillDef
---@field event fun(self: SkillDef, name: '伤害-来源-开始', handler: fun(skill: Skill, damage: Damage): any): SkillDef
---@field event fun(self: SkillDef, name: '伤害-来源-生效前', handler: fun(skill: Skill, damage: Damage): any): SkillDef
---@field event fun(self: SkillDef, name: '伤害-来源-生效后', handler: fun(skill: Skill, damage: Damage): any): SkillDef
---@field event fun(self: SkillDef, name: '伤害-来源-结束', handler: fun(skill: Skill, damage: Damage): any): SkillDef
---@field event fun(self: SkillDef, name: '治疗-目标-开始', handler: fun(skill: Skill, heal: Heal): any): SkillDef
---@field event fun(self: SkillDef, name: '治疗-目标-生效前', handler: fun(skill: Skill, heal: Heal): any): SkillDef
---@field event fun(self: SkillDef, name: '治疗-目标-生效后', handler: fun(skill: Skill, heal: Heal): any): SkillDef
---@field event fun(self: SkillDef, name: '治疗-目标-结束', handler: fun(skill: Skill, heal: Heal): any): SkillDef
---@field event fun(self: SkillDef, name: '治疗-来源-开始', handler: fun(skill: Skill, heal: Heal): any): SkillDef
---@field event fun(self: SkillDef, name: '治疗-来源-生效前', handler: fun(skill: Skill, heal: Heal): any): SkillDef
---@field event fun(self: SkillDef, name: '治疗-来源-生效后', handler: fun(skill: Skill, heal: Heal): any): SkillDef
---@field event fun(self: SkillDef, name: '治疗-来源-结束', handler: fun(skill: Skill, heal: Heal): any): SkillDef
---@field event fun(self: SkillDef, name: string, handler: fun(skill: Skill, ...: any): any): SkillDef
---@field event fun(self: SkillDef, name: '判定-前', handler: fun(skill: Skill, judge: Judge): any): SkillDef
---@field event fun(self: SkillDef, name: '判定-后', handler: fun(skill: Skill, judge: Judge): any): SkillDef
---@field globalEvent fun(self: SkillDef, name: '判定-前', handler: fun(skill: Skill, judge: Judge): any): SkillDef
---@field globalEvent fun(self: SkillDef, name: '判定-后', handler: fun(skill: Skill, judge: Judge): any): SkillDef
---@field globalEvent fun(self: SkillDef, name: string, handler: fun(skill: Skill, ...: any): any): SkillDef

--- 牌订阅时机的声明（与技能同形）：`event` 订**这张牌的主人**那份（`owner:on`）、`globalEvent` 订局那份（`game:on`）—— **只做订阅**，要不要发动由回调自己写（`card:cast(…)`）
--- 内容侧时机（伤害 / 治疗）在这里按名收窄载荷
---@class CardDef
---@field event fun(self: CardDef, name: '伤害-目标-开始', handler: fun(card: Card, damage: Damage): any): CardDef
---@field event fun(self: CardDef, name: '伤害-目标-生效前', handler: fun(card: Card, damage: Damage): any): CardDef
---@field event fun(self: CardDef, name: '伤害-目标-生效后', handler: fun(card: Card, damage: Damage): any): CardDef
---@field event fun(self: CardDef, name: '伤害-目标-结束', handler: fun(card: Card, damage: Damage): any): CardDef
---@field event fun(self: CardDef, name: '伤害-来源-开始', handler: fun(card: Card, damage: Damage): any): CardDef
---@field event fun(self: CardDef, name: '伤害-来源-生效前', handler: fun(card: Card, damage: Damage): any): CardDef
---@field event fun(self: CardDef, name: '伤害-来源-生效后', handler: fun(card: Card, damage: Damage): any): CardDef
---@field event fun(self: CardDef, name: '伤害-来源-结束', handler: fun(card: Card, damage: Damage): any): CardDef
---@field event fun(self: CardDef, name: '治疗-目标-开始', handler: fun(card: Card, heal: Heal): any): CardDef
---@field event fun(self: CardDef, name: '治疗-目标-生效前', handler: fun(card: Card, heal: Heal): any): CardDef
---@field event fun(self: CardDef, name: '治疗-目标-生效后', handler: fun(card: Card, heal: Heal): any): CardDef
---@field event fun(self: CardDef, name: '治疗-目标-结束', handler: fun(card: Card, heal: Heal): any): CardDef
---@field event fun(self: CardDef, name: '治疗-来源-开始', handler: fun(card: Card, heal: Heal): any): CardDef
---@field event fun(self: CardDef, name: '治疗-来源-生效前', handler: fun(card: Card, heal: Heal): any): CardDef
---@field event fun(self: CardDef, name: '治疗-来源-生效后', handler: fun(card: Card, heal: Heal): any): CardDef
---@field event fun(self: CardDef, name: '治疗-来源-结束', handler: fun(card: Card, heal: Heal): any): CardDef
---@field event fun(self: CardDef, name: string, handler: fun(card: Card, ...: any): any): CardDef
---@field event fun(self: CardDef, name: '判定-前', handler: fun(card: Card, judge: Judge): any): CardDef
---@field event fun(self: CardDef, name: '判定-后', handler: fun(card: Card, judge: Judge): any): CardDef
---@field globalEvent fun(self: CardDef, name: '判定-前', handler: fun(card: Card, judge: Judge): any): CardDef
---@field globalEvent fun(self: CardDef, name: '判定-后', handler: fun(card: Card, judge: Judge): any): CardDef
---@field globalEvent fun(self: CardDef, name: string, handler: fun(card: Card, ...: any): any): CardDef
