-- 先基类、再子类（子类要 Extends 父类）—— 装载顺序只在这里负责
include 'core.effect.effect'
include 'core.effect.ask'
include 'core.effect.ask-choice'
include 'core.effect.ask-card'
include 'core.effect.ask-card-with-target'
include 'core.effect.ask-player'
include 'core.effect.ask-use-card'
include 'core.effect.ask-use-card-to-card'
include 'core.effect.ask-use-skill'
include 'core.effect.ask-play-card'
include 'core.effect.ask-offset-card'
include 'core.effect.cast'
include 'core.effect.move-card'
include 'core.effect.use-card'
include 'core.effect.use-card-to-card'
