moe.card        = include 'core.card'
moe.zone        = include 'core.zone'
moe.orderedZone = include 'core.ordered-zone'
moe.random      = include 'core.random'
moe.attribute   = include 'core.attribute'
moe.event       = include 'core.event'
moe.loader      = include 'core.loader'
moe.desk        = include 'core.desk'
moe.player      = include 'core.player'
moe.game        = include 'core.game'
moe.effect      = include 'core.effect'
moe.useCard     = include 'core.use-card'
moe.damage      = include 'core.damage'

return moe
